<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>X4ModManager</AssemblyName>
    <RootNamespace>X4ModManager</RootNamespace>
    <Version>0.2.0</Version>
    <Product>X4 mod管理器</Product>
    <Description>轻量级 X4: Foundations 本地 MOD 管理器</Description>
    <ApplicationIcon>Assets\X4ModManager.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\X4ModManager.Core\X4ModManager.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\X4ModManager.ico" />
  </ItemGroup>
</Project>

